### ISSUE TITLE
Doesn't support  priv-1.9 style page table entries

### ISSUE THREAD

**Issue by neuschaefer** [lowRISC/rocket#3]
While trying to run coreboot/linux on `lowrisc-chip`, I noticed that it doesn't support the page table format described in the Privileged Architecture Specification, version 1.9, whereas [UCB's Rocket](https://github.com/ucb-bar/rocket) does.

**Comment by wsong83** [comment]
No, we do not have it now. A short reason is, we do not have enough man power to keep in sync with the update in ucb-bar/rocket-chip. An update normally happens when we need to make a major release. The next one is probably the end of this year.

**Comment by neuschaefer** [comment]
Thanks for your reply. I will wait, then.

**Comment by wsong83** [comment]
I suppose this is fixed now.
